Quote.destroy_all
Board.destroy_all


oscarWilde1 = Quote.create({ content: "Everyone may not be good, but there's always something good in everyone. Never judge anyone shortly because every saint has a past and every sinner has a future.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde2 = Quote.create({ content: "The truth is rarely pure and never simple.", author: 'Oscar Wilde', quote_details: "`The Importance of Being Earnest`" })
oscarWilde3 = Quote.create({ content: "Be yourself; everyone else is already taken.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde4 = Quote.create({ content: "Crying is for plain women. Pretty women go shopping.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde5 = Quote.create({ content: "It takes a great deal of courage to see the world in all its tainted glory, and still to love it.", author: 'Oscar Wilde', quote_details: "`An Ideal Husband`" })
oscarWilde6 = Quote.create({ content: "Some cause happiness wherever they go; others whenever they go.", author: 'Oscar Wilde', quote_details: "`The Duchess of Padua`" })
oscarWilde7 = Quote.create({ content: "I think it's very healthy to spend time alone. You need to know how to be alone and not be defined by another person.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde8 = Quote.create({ content: "Yes: I am a dreamer. For a dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde9 = Quote.create({ content: "The soul is born old but grows young. That is the comedy of life. And the body is born young and grows old. That is life's tragedy.", author: 'Oscar Wilde', quote_details: "`A Woman of No Importance`" })
oscarWilde10 = Quote.create({ content: "To love oneself is the beginning of a lifelong romance.", author: 'Oscar Wilde', quote_details: "-Lord Goring, `An Ideal Husband`" })
oscarWilde11 = Quote.create({ content: "How foolish is man! He ruins the present while worrying about the future, but weeps in the future by recalling his past!", author: 'Oscar Wilde', quote_details: "" })
oscarWilde12 = Quote.create({ content: "To live is the rarest thing in the world. Most people exist. That is all.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde13 = Quote.create({ content: "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde14 = Quote.create({ content: "An idea that is not dangerous is unworthy of being called an idea at all.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde15 = Quote.create({ content: "I never travel without my diary. One should always have something sensational to read in the train.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde16 = Quote.create({ content: "Life is too important to be taken seriously.", author: 'Oscar Wilde', quote_details: "" })

oscarWilde17 = Quote.create({ content: "To define is to limit.", author: 'Oscar Wilde', quote_details: "" })

oscarWilde18 = Quote.create({ content: "If you want to tell people the truth, make them laugh, otherwise they'll kill you.", author: 'Oscar Wilde', quote_details: "" })

oscarWilde19 = Quote.create({ content: "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde20 = Quote.create({ content: "There are only two tragedies in life: one is not getting what one wants, and the other is getting it.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde21 = Quote.create({ content: "Never love anyone who treats you like you're ordinary.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde22 = Quote.create({ content: "Experience is simply the name we give our mistakes.", author: 'Oscar Wilde', quote_details: "" })

oscarWilde23 = Quote.create({ content: "Imagination was given to man to compensate hom for what he is not, and a sence of humor was provided to console him for what he is.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde24 = Quote.create({ content: "I love acting. It is so much more real than life.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde25 = Quote.create({ content: "I don't want to go to heaven. None of my friends are there.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde26 = Quote.create({ content: "Always forgive your enemies. Nothing annoys them so much.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde27 = Quote.create({ content: "To expect the unexpected shows a thoroughly modern intellect.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde28 = Quote.create({ content: "The books that the world calls immoral are books that show the world its own shame", author: 'Oscar Wilde', quote_details: "`The Picture of Dorain Gray`" })
oscarWilde29 = Quote.create({ content: "How can a woman be expected to be happy with a man who insists on treating her as if she were a perfectly normal human being.", author: 'Oscar Wilde', quote_details: ""})
oscarWilde30 = Quote.create({ content: "No man is rich enough to buy back his past.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde31 = Quote.create({ content: "I am so clever that sometimes I don't understand a single word of what I am saying", author: 'Oscar Wilde', quote_details: ""})
oscarWilde32 = Quote.create({ content: "Ridicule is the tribute paid to the genius by the mediocrities.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde33 = Quote.create({ content: "They've promised that dreams can come true but forgot to mention that nightmares are dreams, too.", author: 'Oscar Wilde', quote_details: "" })
oscarWilde34 = Quote.create({ content: "The public is wonderfully tolerant. It forgives everything except genius.", author: 'Oscar Wilde', quote_details: ""})
oscarWilde35 = Quote.create({ content: "Where there is no love there is no understanding.", author: 'Oscar Wilde', quote_details: "" })

oscarWilde36 = Quote.create({ content: 'You will always be fond of me. I represent to you all the sins you never had the courage to commit.', author: 'Oscar Wilde', quote_details: '`The Picture of Dorian Gray`'  })
#
oscarWilde37 = Quote.create({ content: 'Those who find ugly meanings in beautiful things are corrupt without being charming. This is a fault. Those who find beautiful meanings in beautiful things are the cultivated. For these there is hope. They are the elect to whom beautiful things mean only Beauty. There is no such thing as a moral or an immoral book. Books are well written, or badly written. That is all.', author: 'Oscar Wilde', quote_details: '`The Picture of Dorian Gray`'  })




# VOLTAIRE
voltaire1 = Quote.create({ content: "I do not agree with what you have to say, but I'll defend to the death your right to say it.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire2 = Quote.create({ content: "The longer we dwell on our misfortunes, the greater their power to harm us.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire3 = Quote.create({ content: "Appreciation is a wonderful thing; it makes what is excellent in others belong to us as well.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire4 = Quote.create({ content: "It is difficult to free fools from the chains they revere.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire5 = Quote.create({ content: "Judge a man by his questions rather than his answers.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire6 = Quote.create({ content: "It is dangerous to be right in matters on which the established authorities are wrong.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire7 = Quote.create({ content: 'Love is a canvas furnished by nature and embroidered by imagination.', author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire8 = Quote.create({ content: "What is tolerance? It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each other's folly - that is the first law of nature.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire9 = Quote.create({ content: "Every man is guilty of all the good he didn't do.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire10 = Quote.create({ content: "Don't think money does everything or you are going to end up doing everything for money.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire11 = Quote.create({ content: "If you want to know who controls you, look at who you are not allowed to criticize.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire12 = Quote.create({ content: "It is better to risk saving a guilty man than to condemn an innocent one.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire13 = Quote.create({ content: "No problem can withstand the assault of sustained thinking.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire14 = Quote.create({ content: "Think for yourself and let others enjoy the privilege of doing so too.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire15 = Quote.create({ content: "It is forbidden to kill; therefore all murderers are punished unless they kill in large numbers and to the sound of trumpets.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire16 = Quote.create({ content: "The more often a stupidity is repeated, the more it gets the appearance of wisdom.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire17 = Quote.create({ content: "Men who are occupied in the restoration of health to other men, by the joint exertion of skill and humanity, are above all the great of the earth. They even partake of divinity, since to preserve and renew is almost as noble as to create.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire18 = Quote.create({ content: "God gave us the gift of life; it is up to us to give ourselves the gift of living well.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire19 = Quote.create({ content: "Be it observed, that the most superstitious times have always been those of the most horrible crimes.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire20 = Quote.create({ content: "The more I read, the more I acquire, the more certain I am that I know nothing.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire21 = Quote.create({ content: "Doctors are men who prescribe medicines of which they know little, to cure diseases of which they know less, in human beings of whom they know nothing.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire22 = Quote.create({ content: "So long as the people do not care to exercise their freedom, those who wish to tyrannize will do so; for tyrants are active and ardent, and will devote themselves in the name of any number of gods, religious and otherwise, to put shackles upon sleeping men.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })
voltaire23 = Quote.create({ content: "Let us read, and let us dance; these two amusements will never do any harm to the world.", author: "François-Marie d'Arouet (Voltaire)", quote_details: "" })

# Geoffrey Chaucer
chaucer1 = Quote.create({ content: "What is better than wisdom? Woman. And what is better than a good woman? Nothing.", author: "Geoffrey Chaucer", quote_details: "" })
chaucer2 = Quote.create({ content: "Life is short. Art long. Opportunity is fleeting. Experience treacherous. Judgement difficult.", author: "Geoffrey Chaucer", quote_details: "" })
chaucer3 = Quote.create({ content: "Purity in body and heart May please some -- as for me, I make no boast. For, as you know, no master of a household Has all of his utensils made of gold; Some are wood, and yet they are of use.", author: "Geoffrey Chaucer", quote_details: '`The Canterbury Tales`' })
chaucer4 = Quote.create({ content: "How potent is the fancy! People are so impressionable, they can die of imagination.", author: "Geoffrey Chaucer", quote_details: "" })
chaucer5 = Quote.create({ content: "I will eviscerate you in fiction. Every pimple, every character flaw. I was naked for a day; you will be naked for eternity.", author: "Geoffrey Chaucer", quote_details: "A Knight's Tale, `The Canterbury Tales`" })
chaucer6 = Quote.create({ content: "Love will not be constrain'd by mastery. When mast'ry comes, the god of love anon Beateth his wings, and , farewell, he is gone. Love is a thing as any spirit free.", author: "Geoffrey Chaucer", quote_details: "" })
chaucer7 = Quote.create({ content: "By God, if women had written stories, As clerks had within here oratories, They would have written of men more wickedness Than all the mark of Adam may redress.", author: "Geoffrey Chaucer", quote_details: "`The Wife of Bath's Prologue and Tale`" })
chaucer8 = Quote.create({ content: "Yet do not miss the moral, my good men. For Saint Paul says that all that's written well Is written down some useful truth to tell. Then take the wheat and let the chaff lie still.", author: "Geoffrey Chaucer", quote_details: "`The Canterbury Tales`" })
chaucer9 = Quote.create({ content: "If no love is, I God, what fele I so? And if love is, what thing and which is he? If love be good, from whennes cometh my woo? If it be wikke, a wonder thynketh me.", author: "Geoffrey Chaucer", quote_details: "" })
chaucer10 = Quote.create({ content: "For if a priest be foul, on whom we trust, No wonder is a common man should rust", author: "Geoffrey Chaucer", quote_details: '`The Prologue of Canterbury Tales`' })
chaucer11 = Quote.create({ content: "And high above, depicted in a tower, Sat Conquest, robed in majesty and power, Under a sword that swung above his head, Sharp-edged and hanging by a subtle thread.", author: "Geoffrey Chaucer", quote_details: "`The Canterbury Tales`" })
chaucer12 = Quote.create({ content: "O woman's counsel is so often cold! A woman's counsel brought us first to woe, Made Adam out of Paradise to go Where he had been so merry, so well at ease.", author: "Geoffrey Chaucer", quote_details: "`The Canterbury Tales`" })
chaucer13 = Quote.create({ content: "Three years went by in happiness and health; He bore himself so well in peace and war That there was no one Theseus valued more.", author: "Geoffrey Chaucer", quote_details: "`The Canterbury Tales`" })
chaucer14 = Quote.create({ content: "Thus in this heaven he took his delight And smothered her with kisses upon kisses Till gradually he came to know where bliss is.", author: "Geoffrey Chaucer", quote_details: "`Troilus and Criseyde`" })







# cite1 = Quote.create({ content: "", author: "", quote_details: "" })
# cite2 = Quote.create({ content: "", author: "", quote_details: "" })
# cite3 = Quote.create({ content: "", author: "", quote_details: "" })
# cite4 = Quote.create({ content: "", author: "", quote_details: "" })
# cite5 = Quote.create({ content: "", author: "", quote_details: "" })
# cite6 = Quote.create({ content: "", author: "", quote_details: "" })
# cite7 = Quote.create({ content: "", author: "", quote_details: "" })
# cite8 = Quote.create({ content: "", author: "", quote_details: "" })
# cite9 = Quote.create({ content: "", author: "", quote_details: "" })
# cite10 = Quote.create({ content: "", author: "", quote_details: "" })
# cite11 = Quote.create({ content: "", author: "", quote_details: "" })
# cite12 = Quote.create({ content: "", author: "", quote_details: "" })
# cite13 = Quote.create({ content: "", author: "", quote_details: "" })
# cite14 = Quote.create({ content: "", author: "", quote_details: "" })
# cite15 = Quote.create({ content: "", author: "", quote_details: "" })
# cite16 = Quote.create({ content: "", author: "", quote_details: "" })
# cite17 = Quote.create({ content: "", author: "", quote_details: "" })
# cite18 = Quote.create({ content: "", author: "", quote_details: "" })
# cite19 = Quote.create({ content: "", author: "", quote_details: "" })
# cite20 = Quote.create({ content: "", author: "", quote_details: "" })


# BEETHOVEN

beethoven1 = Quote.create({ content: "Music is the mediator between the spiritual and the sensual life.Although the spirit be not master of that which it creates through music, yet it is blessed in this creation, which, like every creation of art, is mightier than the artist.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven2 = Quote.create({ content: "Don't only practice your art, but force your way into its secrets; for it and knowledge can raise man to the divine.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven3 = Quote.create({ content: "There are no barriers for a person with talent and love towards work.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven4 = Quote.create({ content: "Music is the one incorporeal entrance into the higher world of knowledge which comprehends mankind but which mankind cannot comprehend.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven5 = Quote.create({ content: "I do not know any other sign of superiority but kindness.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven6 = Quote.create({ content: "Prince, what you are, you are by accident of birth what I am, I am of myself. There are and will be thousands of princes. There is only one Beethoven.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven7 = Quote.create({ content: "My thoughts go out to you, my immortal beloved... I can live only wholly with you or not at all.", author: "Ludwig van Beethoven", quote_details: "A mystery woman, 1812" })
beethoven8 = Quote.create({ content: "Music is a higher revelation than all wisdom and philosophy.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven9 = Quote.create({ content: "The main distinction of a human being is persistence in overcoming the most cruel obstacles.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven10 = Quote.create({ content: "I couldn't leave this world before I did everything in this life I was destined to do.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven11 = Quote.create({ content: "Music should strike the fire from the heart of man, and bring tears from the eyes of woman.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven12 = Quote.create({ content: "We mortals with immortal minds are only born for sufferings and joys, and one could almost say that the most excellent receive joy through sufferings.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven13 = Quote.create({ content: "To play a wrong note is insignificant; to play without passion is inexcusable.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven14 = Quote.create({ content: "I have never thought of writing for reputation and honour. What I have in my heart must come out; that is the reason why I compose.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven15 = Quote.create({ content: "The world is a king, and like a king, desires flattery in return for favor; but true art is selfish and perverse - it will not submit to the mold of flattery.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven16 = Quote.create({ content: "It is my belief one should not belittle the artist; while, however glorious his fame may seem, his time on Mount Olympus as an honourable guest of Zeus is short. It's a pity, but all too eager will the common folk drag him from this etherial heights to the low and trodden earth.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven17 = Quote.create({ content: "No friend have I. I must live by myself alone; but I know well that God is nearer to me than others in my art, so I will walk fearlessly with Him.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven18 = Quote.create({ content: "Then let us all do what is right, strive with all our might toward the unattainable, develop as fully as we can the gifts God has given us, and never stop learning.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven19 = Quote.create({ content: "All my life I have regarded myself as one of Mozart's greatest admirers, and I will remain one until my last breath.", author: "Ludwig van Beethoven", quote_details: "" })
beethoven20 = Quote.create({ content: "Oh continue to love me - never misjudge the most faithful heart of your beloved. ever thing ever mine ever ours", author: "Ludwig van Beethoven", quote_details: "" })



mozart1 = Quote.create({ content: "All I insist on, and nothing else, is that you should show the whole world that you are not afraid. Be silent, if you choose; but when it is necessary, speak -- and speak in such a way that people will remember it.", author: "Wolfgang Amadeus Mozart", quote_details: "" })
# mozart2 = Quote.create({ content: "", author: "Wolfgang Amadeus Mozart", quote_details: "" })
# mozart3 = Quote.create({ content: "", author: "Wolfgang Amadeus Mozart", quote_details: "" })



# MARCUS Aurelius
aurelius1 = Quote.create({ content: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius", quote_details: "" })
aurelius2 = Quote.create({ content: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", quote_details: "" })
aurelius3 = Quote.create({ content: "And, to say all in a word, everything which belongs to the body is a stream, and what belongs to the soul is a dream and vapour, and life is a warfare and a stranger's sojourn, and after- fame is oblivion.", author: "Marcus Aurelius", quote_details: "Meditations 167 ACE" })
aurelius4 = Quote.create({ content: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius", quote_details: "" })
aurelius5 = Quote.create({ content: "Be content with what you are, and wish not change; nor dread your last day, nor long for it.", author: "Marcus Aurelius", quote_details: "" })
aurelius6 = Quote.create({ content: "When you arise in the morning, think of what a precious privilege it is to be alive- to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius", quote_details: "" })
aurelius7 = Quote.create({ content: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius", quote_details: "" })
aurelius8 = Quote.create({ content: "So other people hurt me? That's their problem. Their character and actions are not mine. What is done to me is ordained by nature, what I do by my own.", author: "Marcus Aurelius", quote_details: "" })
aurelius9 = Quote.create({ content: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius", quote_details: "" })
aurelius10 = Quote.create({ content: "Whenever you are about to find fault with someone, ask yourself the following question: what fault of mine most nearly resembles the one I am about to criticize?", author: "Marcus Aurelius", quote_details: "" })
aurelius11 = Quote.create({ content: "The only wealth which you will keep forever is the wealth you have given away.", author: "Marcus Aurelius", quote_details: "" })
aurelius12 = Quote.create({ content: "Live a good life. If there are gods and they are just, then they will not care how devout you have been, but will welcome you based on the virtues you have lived by. If there are gods, but unjust, then you should not want to worship them. If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones.", author: "Marcus Aurelius", quote_details: "" })
aurelius13 = Quote.create({ content: "Say to yourself in the early morning: I sahll meet today inquisitive, ungrateful, violent, treacherous, envious, uncharitable men. All these things have come upon them through ignorance of real good and ill.", author: "Marcus Aurelius", quote_details: "" })
aurelius14 = Quote.create({ content: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", quote_details: "" })
aurelius15 = Quote.create({ content: "The object in life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius", quote_details: "" })
aurelius16 = Quote.create({ content: "Can we wonder that men perish and are forgotten, when their noblest and most enduring works decay? Death comes even to monumental structures, and oblivion rests on the most illustrious names.", author: "Marcus Aurelius", quote_details: "" })
aurelius17 = Quote.create({ content: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius", quote_details: "" })
aurelius18 = Quote.create({ content: "The universal order and the personal order are nothing but different expressions and manifestations of a common underlying principle.", author: "Marcus Aurelius", quote_details: "" })
aurelius19 = Quote.create({ content: "Spend your brief moment according to nature's law, and serenely greet the journey's end as an olive falls when it is ripe, blessing the branch that bare it, and giving thanks to the tree that gave it life.", author: "Marcus Aurelius", quote_details: "" })
aurelius20 = Quote.create({ content: "I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinions of himself than on the opinions of others.", author: "Marcus Aurelius", quote_details: "" })
aurelius21 = Quote.create({ content: "It is not death that man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius", quote_details: "" })


# Arthur Conan Doyle
doyle1 = Quote.create({ content: "My mind rebels at stagnation. Give me problems, give me work, give me the most abstruse cryptogram or the most intricate analysis, and I am in my own proper atmosphere. I can dispense then with artificial stimulants. But I abhor the dull routine of existence. I crave for mental exaltation. That is why I have chosen my own particular profession, or rather created it, for I am the only one in the world.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Sign of Four`, 1890" })
doyle2 = Quote.create({ content: "I never guess. It is a shocking habit destructive to the logical faculty.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Sign of Four`, 1890"})
doyle3 = Quote.create({ content: "For strange effects and extraordinary combinations we must go to life itself, which is always far more daring than any effort of the imagination.", author: "Sir Arthur Conan Doyle", quote_details:  "`The Adventures of Sherlock Holmes: The Red-Headed League`, 1891"})
doyle4 = Quote.create({ content: "It is an old maxim of mine that when you have excluded the impossible, whatever remains, however improbable, must be the truth.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Adventure of the Beryl Coronet`, 1892"})
doyle5 = Quote.create({ content: "I consider that a man's brain originally is like a little empty attic, and you have to stock it with such furniture as you choose.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: A Study in Scarlet`, 1887"})
doyle6 = Quote.create({ content: "'You see, my dear Watson,' -he propped his test-tube in the rack, and began to lecture with the air of a professor addressing his class- 'it is not really difficult to construct a series of inferences, each dependent upon its predecessor and each simple in itself. If, after doing so, one simply knocks out all the central inferences and presents one's audience with the starting-point and the conclusion, one may produce a startling, though possibly a meretricious, effect.", author: "Sir Arthur Conan Doyle", quote_details: "-Sherlock Holmes explaining his deduction method to Dr. John Watson, `The Adventures of Sherlock Holmes: The Adventure of the Dancing Men`, 1903"})
doyle7 = Quote.create({ content: "What you do in this wordl is a matter of no consequence... The question is, what can you make people believe that you have done.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: A Study in Scarlet`, 1887"})
doyle8 = Quote.create({ content: "For strange effects and extraordinary combinations we must go to life itself, which is always far more daring than any effort of the imagination.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Red-Headed League`, 1891"})
doyle9 = Quote.create({ content: "But love is an emotional thing, and whatever is emotional is opposed to that true cold reason which I place above all things.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Sign of Four`, 1890"})
doyle10 = Quote.create({ content: "Mediocrity knows nothing higher than itself, but talent instantly recognizes genius.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: Valley of Fear`, 1915" })
doyle11 = Quote.create({ content: "Why on earth people who have something to say which is worth hearing should not take the slight trouble to learn how to make it heard is one of the strange mysteries of modern life.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Lost World`, 1912"})
doyle12 = Quote.create({ content: "You have a grand gift for silence, Watson. It makes you quite invaluable as a companion.", author: "Sir Arthur Conan Doyle", quote_details: "-Sherlock Holmes, `The Adventures of Sherlock Holmes: The Man with the Twisted Lip`, 1891"})
doyle13 = Quote.create({ content: "I have seen too much not to know that the impression of a woman may be more valuable than the conclusion of an analytical reasoner.", author: "Sir Arthur Conan Doyle", quote_details: "`The New Revelation`, 1917"})
doyle14 = Quote.create({ content: "Violence does, in truth recoil upon the violent, and the schemer falls into the pit which he digs for another.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Adventure of the Speckled Band`, 1892"})
doyle15 = Quote.create({ content: "The world is full of obvious things which nobody by any chance ever observes.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Hound of the Baskervilles`, 1902"})
doyle16 = Quote.create({ content: "Mediocrity knows nothing higher than itself, but talent instantly recognizes genius.", author: "Sir Arthur Conan Doyle", quote_details: "`A Story of Waterloo` adapted from his own short story `A Straggler of '15` Play premiered at the Prince's Theatre in Bristol, UK, on 21st of September 1894."})
doyle17 = Quote.create({ content: "Crime is common. Logic is rare. Therefore it is upon the logic rather than upon the crime you should dwell.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Adventure of the Copper Beeches`, 1892"})
doyle18 = Quote.create({ content: "It is a pity he did not write in pencil. As you have no doubt frequently observed, the impression usually goes through- a fact which has dissolved many a happy marriage.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: The Return of Sherlock Holmes`, 1905"})
doyle19 = Quote.create({ content: "What you do in this world is a matter of no consequence. The question is what can you make people believe you have done.", author: "Sir Arthur Conan Doyle", quote_details: "`The Adventures of Sherlock Holmes: A Study in Scarlet`, 1887"})



#  Queen Elizabeth I

goldenAge1 = Quote.create({ content: "Fear not, we are of the nature of the lion, and cannot descend to the destruction of mice and such small beasts.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge2 = Quote.create({ content: "I do not want a husband who honours me as a queen, if he does not love me as a woman.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge3 = Quote.create({ content: "Though the sex to which I belong is considered weak you will nevertheless find me a rock that bends to no wind.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge4 = Quote.create({ content: "I know I have the body of a weak and feeble woman, bu I have the heart and stomach of a king, and a king of England too.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge5 = Quote.create({ content: "I do not so much rejoice that God hath made me to be a Queen, as to be a Queen over so thankful a people.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge6 = Quote.create({ content: "To be a king and wear a crown is a thing more glorious to them that see it than it is pleasant to them that bear it.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge7 = Quote.create({ content: "I am Elizabeth Tudor and I will bow to no man. I will face every threat to my reign with sword in hand and any who stand in my way shall fall.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge8 = Quote.create({ content: "I will be tried by envy itself. I need not to use many words, for my deeds do try me.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge9 = Quote.create({ content: "I would rather be a beggar and single than a queen and married.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge10 = Quote.create({ content: "I shall lend credit to nothing against my people which parents would not believe against their own children.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge11 = Quote.create({ content: "I am your annointed Queen. I will never be by violence constrained to do anything. I thank God I am endued with such qualities that if I were turned out of the Realm in my petticoat I were able to live in any place in Christendom.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge12 = Quote.create({ content: "Do not tell secrets to those whose faith and silence you have not already tested.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge13 = Quote.create({ content: "There is no jewel, be it of never so rich a price, which I set before this jewel: I mean your love.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge14 = Quote.create({ content: "There is one thing higher than Royalty: and that is religion, which causes us to leave the world, and seek God.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge15 = Quote.create({ content: "I have already joined myself in marriage to a husband, namely the kingdom of England.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge16 = Quote.create({ content: "Although I may not be lioness, I am a lion's cub, and inherit many of his qualities; and as long as the King of France treats me gently he will find me as gentle and tractable as he can desire; but if he be rough, I shall take the trouble to be just as troublesome and offensive to him as I can.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge17 = Quote.create({ content: "When we hang on to resentment, we poison ourselves. As compulsive overeaters, we cannot afford resentment, since it exacerbates our disease.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge18 = Quote.create({ content: "When I was fair and young, and favour graced me, Of many was I sought, their mistress for to be; But I did scorn them all, and answered them therefore, `Go, go, go seek some otherwhere! Importune me no more!`", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge19 = Quote.create({ content: "Monarchs ought to put to death the authors and instigators of war, as their sworn enemies and as dangers to their states.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge20 = Quote.create({ content: "My mortal foe can no ways wish me a greater harm than England's hate; neither should death be less welcome unto me than such a mishap betide me.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge21 = Quote.create({ content: "There is no marvel in a woman learning to speak, but there would be in teaching her to hold her tongue.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge22 = Quote.create({ content: "Little man, the word `must` is not to be used to princes.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge23 = Quote.create({ content: "Let the good service of well-deservers be never rewarded with loss. Let their thanks be such as may enourage more strivers for the like.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge24 = Quote.create({ content: "If I should say the sweetest speech with the eloquentest tongue that ever was in man, I were not able to express that restless care which I have ever bent to govern for the greatest wealth.", author: "Queen Elizabeth I of England", quote_details: "" })
goldenAge25 = Quote.create({ content: "Then she is too high, for I myself am neither too high nor too low.", author: "Queen Elizabeth I of England", quote_details: "On being told Mary, Queen of Scots, was taller than she" })


# Churchill

churchill1 = Quote.create({ content: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill", quote_details: ""})
churchill2 = Quote.create({ content: "Diplomacy is the art of telling people to go to hell in such a way that they ask for directions.", author: "Winston Churchill", quote_details: ""})
churchill3 = Quote.create({ content: "Everyone is in favour of free speech. Hardly a day passes without its being extolled, but some people's idea of it is that they are free to say what they like, but if anyone else says anything back, that is an outrage.", author: "Winston Churchill", quote_details: ""})
churchill4 = Quote.create({ content: "Things are not always right because they are hard, but if they are right one must not mind if they are also hard.", author: "Winston Churchill", quote_details: ""})
churchill5 = Quote.create({ content: "A lie gets halfway around the world before the truth has a chance to get its pants on.", author: "Winston Churchill", quote_details: ""})
churchill6 = Quote.create({ content: "Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen.", author: "Winston Churchill", quote_details: ""})
churchill7 = Quote.create({ content: "A pessimist seeds the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill", quote_details: ""})
churchill8 = Quote.create({ content: "You will never reach your destination if youstop and throw strones at every dog that barks.", author: "Winston Churchill", quote_details: ""})
churchill9 = Quote.create({ content: "This is no war of chieftains or of princes, of dynasties or national ambition; it is a war of people and of causes. There are vast numbers, not only in this island but in every land, who will render faithful service in this war but whose names will never be known, whose deeds will never be recorded. This is a war of the Unknown Warriors; but let all strive without failing in faith or in duty, and the dark curse of Hitler will be lifted from our age.", author: "Winston Churchill", quote_details: "Radio broadcast, 14 July 1940"})
churchill10 = Quote.create({ content: "I would say to the House... `I have nothing to offer but blood, toil, tears and sweat`... Victory at all costs, victory in spite of all terror, victory however long and hard the road may be; for without victory there is no survival.", author: "Winston Churchill", quote_details: "Churchill's first speech as Prime Minister, House of Commons, 13 May 1940"})
churchill11 = Quote.create({ content: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", quote_details: ""})
churchill12 = Quote.create({ content: "A man does what he must- in spite of personal consequences, in spite of obstacles and dangers and pressures- and that is the basis of all human morality.", author: "Winston Churchill", quote_details: ""})
churchill13 = Quote.create({ content: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: "Winston Churchill", quote_details: ""})
churchill14 = Quote.create({ content: "You are the master of your unspoken words, but a slave to the words you have spoken.", author: "Winston Churchill", quote_details: ""})
churchill15 = Quote.create({ content: "We have our own dream and our own task. We are with Europe, but not of it. We are linked but not combined. We are interested and associated but not absorbed. If Britain must choose between Europe and the open sea, she must always choose the open sea.", author: "Winston Churchill", quote_details: "House of Commons, 11 May 1953"})
churchill16 = Quote.create({ content: "Men occasionally stumble over the truth, but most of them pick themselves up and hurry off as if nothing ever happened.", author: "Winston Churchill", quote_details: ""})
churchill17 = Quote.create({ content: "The best argument against democracy is a five-minute conversation with the average voter.", author: "Winston Churchill", quote_details: ""})
churchill18 = Quote.create({ content: "To improve is to change to be perfect is to change often.", author: "Winston Churchill", quote_details: ""})
churchill19 = Quote.create({ content: "Continuous efforts- not strength or intelligence- is the key to unlocking our potential.", author: "Winston Churchill", quote_details: ""})
churchill20 = Quote.create({ content: "My most brilliant achievement was my ability to be able to persuade my wife to marry me.", author: "Winston Churchill", quote_details: ""})
churchill21 = Quote.create({ content: "If you're not a liberal at twenty you have no heart, if you're not a conservative at forty you have no brain.", author: "Winston Churchill", quote_details: ""})
churchill22 = Quote.create({ content: "Socialism is the philosophy of failure, the creed of ignorance and the gospel of envy. Its inherent virtue is the equal sharing of misery.", author: "Winston Churchill", quote_details: ""})
churchill23 = Quote.create({ content: "If you have an important point to make, don't try to be subtle or clever. Use a pile driver. Hit the point once. Then come back and hit it again. Then hit it a third time- a tremendous whack.", author: "Winston Churchill", quote_details: ""})
churchill24 = Quote.create({ content: "If we open a quarrel between past and present, we shall find that we have lost the future.", author: "Winston Churchill", quote_details: ""})



#  DAVINCI
daVinci1 = Quote.create({ content: "The first step towards getting somewhere is to decide that you are not going to stay where you are.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci2 = Quote.create({ content: "Mechanics is the paradise of the mathematical sciences because by means of it one comes to the fruits of mathematics.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci3 = Quote.create({ content: "The fame of the rich man dies with him; the fame of the treasure, and not of the man who possessed it, remains.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci4 = Quote.create({ content: "As every divided kingdom falls, so every mind divided between many studies confounds and saps itself.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci5 = Quote.create({ content: "To develop a complete mind: study the science of art; study the art of science. Learn how to see. Realize that everything connects to everything else.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci6 = Quote.create({ content: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass and never knows where he may cast.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci7 = Quote.create({ content: "Beauty perishes in life, but is immortal in art.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci8 = Quote.create({ content: "Having wandered some distance among gloomy rocks, I came to the entrance of a great cavern... Two contrary emotions arose in me: fear and desire-fear of the threatening dark cavern, desire to see whether there were any marvelous things in it.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci9 = Quote.create({ content: "If man wants freedom why keep birds and animals in cages? Truly man is the king of beasts for his brutality exceeds them. We live by the death of others. We are burial places! I have since an early age abjured the use of meat.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci10 = Quote.create({ content: "Just as courage is the danger of life, so is fear its safegaurd.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci11 = Quote.create({ content: "There are three classes of people: Those who see. Those who see when they are shown. Those who do not see.", author: 'Leonardo da Vinci', quote_details: "" })

daVinci12 = Quote.create({ content: "Medicine is the restoration of discordant elements; sickness is the discord of the elements infused into the living body.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci13 = Quote.create({ content: "The wisest and noblest teacher is nature itself.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci14 = Quote.create({ content: "The greatest deception men suffer is from their own opinions.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci15 = Quote.create({ content: "As every divided kingdom falls, so every mind divided between many studies confounds and saps itself.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci16 = Quote.create({ content: "Learning acquired in youth arrests the evil of old age; and if you understand that old age has wisdom for its food, you will so conduct yourself in youth that your old age will not lack for nourishment.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci17 = Quote.create({ content: "I love those who can smile in trouble, who can gather strength from distress, and grow brave by reflection. 'Tis the business of little minds to shrink, but they whose heart is firm, and whose conscience approves their conduct, will pursue their principles unto death.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci18 = Quote.create({ content: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci19 = Quote.create({ content: "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci20 = Quote.create({ content: "Feathers shall raise men even as they do birds towards heaven:- That is by letters written with their quills.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci21 = Quote.create({ content: "He who wishes to be rich in a day will be hanged in a year.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci22 = Quote.create({ content: "All our knowledge has its origin in our perceptions.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci23 = Quote.create({ content: "Time abides long enough for those who make use of it.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci24 = Quote.create({ content: "Why does the eye see a thing more clearly in dreams than the imagination when awake?", author: 'Leonardo da Vinci', quote_details: "" })
daVinci25 = Quote.create({ content: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci26 = Quote.create({ content: "As a well spent day brings happy sleep so life well used brings happy death.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci27 = Quote.create({ content: "I awoke, only to see that the rest of the world is still asleep.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci28 = Quote.create({ content: "While I thought that I was learning how to live, I have been learning how to die.", author: 'Leonardo da Vinci', quote_details: "" })
daVinci29 = Quote.create({ content: "Learn how to see. Realize that everything connects to everything else.", author: 'Leonardo da Vinci', quote_details: "" })


# Martin Luther King Jr.
mlk1 = Quote.create({  content: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", quote_details: "" })
mlk2 = Quote.create({  content: "If you can't fly, then run, if you can't run, then walk, if you can't walk, then crawl, but whatever you do, you have to keep moving forward.", author: "Martin Luther King Jr.", quote_details: "" })
mlk3 = Quote.create({  content: "We have before us the glorious opportunity to inject a new dimension of love into the veins of our civilization.", author: "Martin Luther King Jr.", quote_details: "" })
mlk4 = Quote.create({  content: "We must accept finite disappointment, but never lose infinite hope.", author: "Martin Luther King Jr.", quote_details: "" })
mlk5 = Quote.create({  content: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr.", quote_details: "" })
mlk6 = Quote.create({  content: "In the End, we will remember not the words of our enimies, but the silence of our friends.", author: "Martin Luther King Jr.", quote_details: "" })
mlk7 = Quote.create({  content: "The function of education is to teach one to think intensively and to think critically. Intelligence plus character - that is the goal of true education.", author: "Martin Luther King Jr.", quote_details: "" })
mlk8 = Quote.create({  content: "Darkness can't drive out darkness; only light can do that. Hate can't drive out hate; only love can do that.", author: "Martin Luther King Jr.", quote_details: "" })
mlk9 = Quote.create({  content: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr.", quote_details: "" })
mlk10 = Quote.create({  content: "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.", author: "Martin Luther King Jr.", quote_details: "" })
mlk11 = Quote.create({  content: "Every man must decide whether he will walk in the light of creative altruism or in the dark of destructive selfishness.", author: "Martin Luther King Jr.", quote_details: "" })
mlk12 = Quote.create({  content: "It is not possible to be in favor of justice for some people and not be in favor of justice for all people.", author: "Martin Luther King Jr.", quote_details: "" })
mlk13 = Quote.create({  content: "I have the audacity to believe that people everywhere can have three meals a day for their bodies; education and culture for their minds; and dignity, equality and freedom for their spirits.", author: "Martin Luther King Jr.", quote_details: "" })
mlk14 = Quote.create({  content: "Commit yourself to the noble struggle for human rights. You will make a greater person of yourself, a greater nation of your country and a finer world to live in.", author: "Martin Luther King Jr.", quote_details: "" })
mlk15 = Quote.create({  content: "True peace is not merely the absence of tension: it is the presnece of justice.", author: "Martin Luther King Jr.", quote_details: "" })
mlk16 = Quote.create({  content: "No person has the right to rain on your dreams.", author: "Martin Luther King Jr.", quote_details: "" })
mlk17 = Quote.create({  content: "Nothing in all the world is more dangerous than sincere ignorance and conscientious stupidity.", author: "Martin Luther King Jr.", quote_details: "" })
mlk18 = Quote.create({  content: "Equality means dignity. And dignity demands a job and a paycheck that lasts through the week.", author: "Martin Luther King Jr.", quote_details: "" })
mlk19 = Quote.create({  content: "Nonviolence is a powerful and just weapon which cuts without wounding and ennobles the man who wields it. It is a sword that heals.", author: "Martin Luther King Jr.", quote_details: "" })
mlk20 = Quote.create({ content: "People fail to get along because they fear each other; they fear each other because they don't know each other; they don't know each other because they have not communicated with each other.", author: "Martin Luther King Jr.", quote_details: ""  })

# DAVINCI
shakespeare1 = Quote.create({ content: "Some are born great, some achieve greatness, and some have greatness thrust upon them.", author: 'William Shakespeare', quote_details: "" })
shakespeare2 = Quote.create({ content: "There is nothing either good or bad, but thinking makes it so.", author: 'William Shakespeare', quote_details: "" })
shakespeare3 = Quote.create({ content: "", author: 'William Shakespeare', quote_details: "" })
shakespeare4 = Quote.create({ content: "I would challenge you to a battle of wits, but I see you are unarmed.", author: 'William Shakespeare', quote_details: "" })
shakespeare5 = Quote.create({ content: "All the world's a stage, and all the men and women merely players: They have their exits and entrances and one man in his time plays many parts.", author: 'William Shakespeare', quote_details: "" })
shakespeare6 = Quote.create({ content: "Better three hours too soon than a minute too late.", author: 'William Shakespeare', quote_details: "" })
shakespeare7 = Quote.create({ content: "We know what we are, but know not what we may be.", author: 'William Shakespeare', quote_details: "" })
shakespeare8 = Quote.create({ content: "Life's but a walking shadow, a poor player, that struts and frets his hour upon the stage, and then is heard no more; it is a tale told by an idiot, full of sound and fury, signifying nothing.", author: 'William Shakespeare', quote_details: "" })
shakespeare9 = Quote.create({ content: "A fool thinks himself to be wise, but a wise man knows himself to be a fool.", author: 'William Shakespeare', quote_details: "" })
shakespeare10 = Quote.create({ content: "When I saw you I fell in love, and you smiled because you knew.", author: 'William Shakespeare', quote_details: "" })
shakespeare11 = Quote.create({ content: "How silver-sweet sound lover's tongues by night, like softest music to attending ears!", author: 'William Shakespeare', quote_details: "" })
shakespeare12 = Quote.create({ content: "Have more than you show, speak less than you know.", author: "" })
shakespeare13 = Quote.create({ content: "These violent delights have violent ends and in their triumph die, like fire and powder which, as they kiss, consume.", author: 'William Shakespeare', quote_details: "" })
shakespeare14 = Quote.create({ content: "Never play with the feelings of others, because you may win the game but the risk is that you will surely lose the person for a life time.", author: 'William Shakespeare', quote_details: "" })
shakespeare15 = Quote.create({ content: "It is not in the stars to hold our destiny but in ourselves.", author: 'William Shakespeare', quote_details: "" })
shakespeare16 = Quote.create({ content: "My bounty is as boundless as the sea, my love as deep; the more I give to thee, the more I have, for both are infinite.", author: 'William Shakespeare', quote_details: "" })
shakespeare17 = Quote.create({ content: "Sorrow breaks seasons and reposing hours, makes the night morning, and the noontide night.", author: 'William Shakespeare', quote_details: "" })
shakespeare18 = Quote.create({ content: "My only love sprung from my only hate! Too early seen unknown, and known too late! Prodigious birth of love it is to me, that I must love a loathed enemy.", author: 'William Shakespeare', quote_details: "" })
shakespeare19 = Quote.create({ content: "Like as the waves make towards the pebbled shore, so do our minutes hasten to their end.", author: 'William Shakespeare', quote_details: "" })
shakespeare20 = Quote.create({ content: "If to do were as easy as to know what were good to do, chapels had been churches, and poor men's cottage princes' palaces.", author: 'William Shakespeare', quote_details: "" })
shakespeare21 = Quote.create({ content: "I'd rather have an enemy who admits they hate me, instead of a friend who secretly puts me down.", author: 'William Shakespeare', quote_details: "" })


# #  HOMER
homer1 = Quote.create({ content: "The gods envy us. They envy us because we're mortal, because any moment may be our last. Everything is more beautiful because we're doomed. You will never be lovlier than you are now. We will never be here again.", author: "Homer", quote_details: "`The Iliad`" })
homer2 = Quote.create({ content: "... There is the heat of Love, the pulsing rush of Longing, the lover's whisper, irresistible - magic to make the sanest man go mad.", author: "Homer", quote_details: "" })
homer3 = Quote.create({ content: "Hateful to me as the gates of Hades is that man who hides one thing in his heart and speaks another.", author: "Homer", quote_details: "" })
homer4 = Quote.create({ content: "Words empty as the wind are best left unsaid.", author: "Homer", quote_details: "" })
homer5 = Quote.create({ content: "Of all creatures that breathe and move upon the earth, nothing is bred that is weaker than man.", author: "Homer", quote_details: "" })
homer6 = Quote.create({ content: "To have a great man for an intimate friend seems pleasant to those who have never tried it; those who have, fear it.", author: "Homer", quote_details: "" })
homer7 = Quote.create({ content: "Be still my heart; thou hast known worse than this.", author: "Homer", quote_details: "" })
homer8 = Quote.create({ content: "There is a time for many words, and there is also a time for sleep.", author: "Homer", quote_details: "" })
homer9 = Quote.create({ content: "There is nothing nobler or more admirable than when two people who see eye to eye keep house as man and wife, confounding their enemies and delighting their friends.", author: "Homer", quote_details: "" })
homer10 = Quote.create({ content: "Wine can of their wits the wise beguile, make the sage folic, and the serious smile.", author: "Homer", quote_details: "" })
homer11 = Quote.create({ content: "Miserable mortals who, like leaves, at one moment flame with life, eating the produce of the land, and at another moment weakly perish.", author: "Homer", quote_details: "" })
homer12 = Quote.create({ content: "Dreams surely are difficult, confusing, and not everything in them is brought to pass for mankind. For fleeting dreams have two gates, one is fashioned of horn and one of ivory. Those which pass through the one of sawn ivory are deceptive, bringing tidings which come to naught, but those which issue from the one of polished horn bring true results when a mortal sees them.", author: "Homer", quote_details: "" })
homer13 = Quote.create({ content: "Evil deeds do not prosper; the slow man catches up with the swift.", author: "Homer", quote_details: "" })
homer14 = Quote.create({ content: "I look at you and a sense of wonder takes me.", author: "Homer", quote_details: "" })
homer15 = Quote.create({ content: "Beware the toils of war... the mesh of the huge dragnet sweeping up the world.", author: "Homer", quote_details: "" })
homer16 = Quote.create({ content: "Wise to resolve, and patient to perform.", author: "Homer", quote_details: "" })
homer17 = Quote.create({ content: "You ought not to practice childish ways, since you are no longer that age.", author: "Homer", quote_details: "" })
homer18 = Quote.create({ content: "It is tedious to tell again tales already plainly told.", author: "Homer", quote_details: "" })
homer19 = Quote.create({ content: "Even a fool learns something once it hits him.", author: "Homer", quote_details: "" })
homer20 = Quote.create({ content: "A small rock holds back a great wave.", author: "Homer", quote_details: "" })


einstein1 = Quote.create({ content: "The difference between stupidity and genius is that genius has its limits.", author: "Albert Einstein" })
einstein2 = Quote.create({ content: "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.", author: "Albert Einstein", quote_details: "" })
einstein3 = Quote.create({ content: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", quote_details: "" })
einstein4 = Quote.create({ content: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein", quote_details: "" })
einstein5 = Quote.create({ content: "Reality is merely an illusion, albeit a very persistent one.", author: "Albert Einstein", quote_details: "" })
einstein6 = Quote.create({ content: "", author: "Albert Einstein", quote_details: "" })
einstein7 = Quote.create({ content: "Stay away from negative people. They have a problem for every solution.", author: "Albert Einstein", quote_details: "" })
einstein8 = Quote.create({ content: "Weak people revenge. Strong people forgive. Intelligent People Ignore.", author: "Albert Einstein", quote_details: "" })
einstein9 = Quote.create({ content: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein", quote_details: "" })
einstein10 = Quote.create({ content: "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.", author: "Albert Einstein", quote_details: "" })
einstein11 = Quote.create({ content: "Two things are infinite. The universe and human stupidity... and I'm not so sure about the universe.", author: "Albert Einstein", quote_details: "" })
einstein12 = Quote.create({ content: "Education is not the learning of facts, but training the mind to think.", author: "Albert Einstein", quote_details: "" })
einstein13 = Quote.create({ content: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miricle.", author: "Albert Einstein", quote_details: "" })
einstein14 = Quote.create({ content: "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.", author: "Albert Einstein", quote_details: "" })
einstein15 = Quote.create({ content: "Only those who attempt the absurd can achieve the impossible.", author: "Albert Einstein", quote_details: "" })
einstein16 = Quote.create({ content: "The only thing that interferes with my learning is my education.", author: "Albert Einstein", quote_details: "" })
einstein17 = Quote.create({ content: "Try not to become a man of success but rather try to become a man of value.", author: "Albert Einstein", quote_details: "" })
einstein18 = Quote.create({ content: "I am thankful for all of those who said NO to me; its because of them I'm doing it myself.",  author: "Albert Einstein", quote_details: "" })
einstein19 = Quote.create({ content: "The person who reads too much and uses his brain too little will fall into lazy habits of thinking.",  author: "Albert Einstein", quote_details: "" })
einstein20 = Quote.create({ content: "Peace cannot be kept by force, it can only be achieved by understanding.",  author: "Albert Einstein", quote_details: "" })
einstein21 = Quote.create({ content: "I have no particular talent. I am merely inquisitive.",  author: "Albert Einstein", quote_details: "" })
einstein22 = Quote.create({ content: "The most beautiful gift of nature is that it gives one pleasure to look around and try to comprehend what we see.",  author: "Albert Einstein", quote_details: "" })
einstein23 = Quote.create({ content: "The intuitive mind is a sacred gift and the rational mind is a faithful servant. We have created a society that honors the servant and has forgotten the gift.",  author: "Albert Einstein", quote_details: "" })
einstein24 = Quote.create({ content: "The whole of science is nothing more than a refinement of everyday thinking.",  author: "Albert Einstein", quote_details: "" })


# #  CHRISTOPHER MARLOWE

marlowe1 = Quote.create({ content: "The difference between stupidity and genius is that genius has its limits.", author: "Christopher Marlowe", quote_details: "" })
marlowe2 = Quote.create({ content: "I count religion but a childish toy, and hold there is no sin but ignorance. Birds of the air will tell of murders past. I am asham'd to hear such fooleries!", author: "Christopher Marlowe", quote_details: "" })
marlowe3 = Quote.create({ content: "O, thou art fairer than the evening air clad in the beauty of a thousand stars.", author: "Christopher Marlowe", quote_details: "" })
marlowe4 = Quote.create({ content: "Hell hath no limits, nor is circumscribed in one self place, for where we are is hell, and where hell is there must we ever be and to be short, when all the world dissolves, and every creature shall be purified, all places shall be hell that are not heaven.", author: "Christopher Marlowe", quote_details: "" })
marlowe5 = Quote.create({ content: "Was this the face that launch'd a thousand ships, and burnt the topless towers of Ilium? Sweet Helen, make me immortal with a kiss! Her lips suck forth my soul: see, where it flies! Come Helen, come give me my soul again. Here will I dwell, for heaven be in these lips, and all is dross that is not Helena.", author: "Christopher Marlowe", quote_details: "" })
marlowe6 = Quote.create({ content: "Blood is the god of war's rich livery.", author: "Christopher Marlowe", quote_details: "" })
marlowe7 = Quote.create({ content: "It is not passing brave to be a King and ride in triumph through Persepolis?", author: "Christopher Marlowe", quote_details: "" })
marlowe8 = Quote.create({ content: "It is a comfort to the miserable to have comrades in misfortune, but it is a poor comfort after all.", author: "Christopher Marlowe", quote_details: "" })
marlowe9 = Quote.create({ content: "Now hast thou but one bare hour to live and then thou must be damned perpetually! Stand still, you ever-moving spheres of heaven, that time may cease and midnight never come.", author: "Christopher Marlowe", quote_details: "" })
marlowe10 = Quote.create({ content: "Why should you love him whom the world hates so? Because he love me more than all the world.", author: "Christopher Marlowe", quote_details: "" })
marlowe11 = Quote.create({ content: "Cut is the branch that might have grown full straight, and burned is Apollo's laurel bough, that sometime grew within this learned man.", author: "Christopher Marlowe", quote_details: "" })
marlowe12 = Quote.create({ content: "Who hateth me but for my happiness? Or who is honoured now but for his wealth? Rather had I, a Jew, be hated thus, than pitied in a Christian poverty.", author: "Christopher Marlowe", quote_details: "" })
marlowe13 = Quote.create({ content: "That perfect bliss and sole felicity, the sweet fruition of an earthly crown.", author: "Christopher Marlowe", quote_details: "" })
marlowe14 = Quote.create({ content: "I am Envy, begotten of a chimney-sweeper and an oyster-wife. I cannot read, and therefore wish all books were burnt; I am lean with seeing others eat - O that there would come a famine through all the world, that all might die, and I live alone; then thou should'st see how fat I would be! But must thou sit and I stand? Come down, with a vengeance!", author: "Christopher Marlowe", quote_details: "" })
marlowe15 = Quote.create({ content: "All live to die; and rise to fall.", author: "Christopher Marlowe", quote_details: "" })
marlowe16 = Quote.create({ content: "Virginity, albeit some highly prize it, compared with marriage, had you tried them both, differs as much as wine and water doth.", author: "Christopher Marlowe", quote_details: "" })
marlowe17 = Quote.create({ content: "I'm armed with more than complete steel, - The justice of my quarrel.", author: "Christopher Marlowe", quote_details: "" })
marlowe18 = Quote.create({ content: "The stars move still, time runs, the clock will strike.", author: "Christopher Marlowe", quote_details: "" })
marlowe19 = Quote.create({ content: "While money doesn't buy love, it puts you in a great bargaining position.", author: "Christopher Marlowe", quote_details: "" })


# PLATO / Aristotle / DARWIN / Churchill / Edgar Allan Poe / Arthur connan doyle(Sherlock Holmes)
# daVinci1 = Quote.create({ author: "", content: "", level_id: __.id })

# # PLATO
plato1 = Quote.create({ content: "Excellence is not a gift, but a skill that takes practice. We do not act 'rightly' because we are 'excellent', in fact we achieve 'excellence' by acting 'rightly'.", author: 'Plato', quote_details: "" })
plato2 = Quote.create({ content: "Good actions give strength to ourselves and inspire good actions in others.", author: 'Plato', quote_details: "" })
plato3 = Quote.create({ content: "The first and greatest victory is to conquer yourself. To be conquered by yourself is of all things most shameful and vile.", author: 'Plato', quote_details: "" })
plato4 = Quote.create({ content: "There will be no end to the troubles of states, or of humanity itself, til philosophers become kings in this world, or til those we now call kings and rulers really and truly become philosophers, and political power and philosophy thus come into the same hands.", author: 'Plato', quote_details: "" })
plato5 = Quote.create({ content: "Democracy... is a charming form of government, full of variety and disorder; and dispensing a sort of equality to equals and unequals alike.", author: 'Plato', quote_details: "" })
plato6 = Quote.create({ content: "The good are unwilling to rule, either for money's sake or for honour. So they must be forced to consent under threat of penalty. The heaviest penalty for declining to rule is to be ruled by someone inferior to yourself. That is the fear, I believe, that decent people accept power.", author: 'Plato', quote_details: "" })
plato7 = Quote.create({ content: "Never discourage anyone who continually makes progress, no matter how slow.", author: 'Plato', quote_details: "" })
plato8 = Quote.create({ content: "Strange times are these in which we live when old and young are taught falsehoods in school. And the person that dares to tell the truth is called at once a lunatic and fool.", author: 'Plato', quote_details: "" })
plato9 = Quote.create({ content: "Every heart sings a song, incomplete, until another heart whispers back. Those who wish to sing always find a song. At the touch of a lover, everyone becomes a poet.", author: 'Plato', quote_details: "" })
plato10 = Quote.create({ content: "Wise men speak because they have something to say; fools because they have to say something.", author: 'Plato', quote_details: "" })
plato11 = Quote.create({ content: "Good people don't need laws to tell them to act responsibly... and bad people will find a way around the laws.", author: 'Plato', quote_details: "" })
plato12 = Quote.create({ content: "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything.", author: 'Plato', quote_details: "" })
plato13 = Quote.create({ content: "Do not train children to learning by force and harshness, but direct them to it by what amuses their minds, so that you may be better able to discover with accuracy the peculiar bent of the genius of each.", author: 'Plato', quote_details: "" })
plato14 = Quote.create({ content: "Only the dead have seen the end of war.", author: 'Plato', quote_details: "" })
plato15 = Quote.create({ content: "Knowledge which is acquired under compulsion obtains no hold on the mind.", author: 'Plato', quote_details: "" })
plato16 = Quote.create({ content: "Opinion is the medium between knowledge and ignorance.", author: 'Plato', quote_details: "" })
plato17 = Quote.create({ content: "Human behaviour flows from three main sources; desire, emotion and knowledge.", author: 'Plato', quote_details: "" })
plato18 = Quote.create({ content: "According to Greek mythology, humans were originally created with four arms, four legs and a head with two faces. Fearing their power, Zeus split them intot wo separate beingsm condemning them to spend their lives in search of their other halves.", author: 'Plato', quote_details: "" })
plato19 = Quote.create({ content: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: 'Plato', quote_details: "" })
plato20 = Quote.create({ content: "False words are not only evil in themselves, but they infect the soul with evil.", author: 'Plato', quote_details: "" })




# # MACHIAVELLI machiavelli
machiavelli1 = Quote.create({ content: 'There are three kinds of intelligence: one kind understands things for itself, the other appreciates what others can understand, the third understands neither for itself nor through others. The first kind is excellent, the second good, and the third kind useless.', author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli2 = Quote.create({ content: "There is no avoiding war; it can only be postponed to the advantage of others.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli3 = Quote.create({ content: "The lion cannot protect himself from traps, and the fox cannot defend himself from wolves. One must therefore be a fox and recognize traps, and a lion to frighten wolves.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli4 = Quote.create({ content: "If and injury has to be done to a man it should be so severe that his vengeance need not be feared.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli5 = Quote.create({ content: "Besides the reasons mentioned, the nature of the people is variable, and whilst it is easy to persuade them, it is difficult to fix them in that persuasion. And thus it is necessary to take such measures that, when they believe no longer, it may be possible to make them believe by force.", author: 'Niccolo Machiavelli', quote_details: "`The Prince`; Chapter 6" })
machiavelli6 = Quote.create({ content: "The sinews of war are not gold, but good soldiers; for gold alone will not procure good soldiers, but good soldiers will always procure gold.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli7 = Quote.create({ content: "The wise man does at once what the fool does finally.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli8 = Quote.create({ content: "Respect those who are generous not those who could be generous.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli9 = Quote.create({ content: "Upon this question arises: whether it be better to be loved than feared or feared than loved? It may be answered that one should wish to be both, but, because it is difficult to unite them in one person, it is much safer to be feared than loved, when, of the two, either must be dispensed with.", author: 'Niccolo Machiavelli', quote_details: "`The Prince`: Chapter 17" })
machiavelli10 = Quote.create({ content: "There is nothing more difficult to take in hand, more perilous to conduct, or more uncertain in its success, than to take the lead in the introduction of a new order of things.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli11 = Quote.create({ content: "The more sand has escaped from the hourglass of our life, the clearer we should see through it.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli12 = Quote.create({ content: "Entrepreneurs are simply those who understand that there is a difference between obstacle and opportunity and are able to turn both to their advantage.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli13 = Quote.create({ content: "All courses of action are risky, so prudence is not in avoiding danger (it's impossible), but calculating risk and acting decisively. Make mistakes of ambition and not mistakes of sloth. Develop the strength to do bold things, not the strength to suffer.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli14 = Quote.create({ content: "Everyone sees what you appear to be, few experience what you really are.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli15 = Quote.create({ content: "To understand the nature of the people one must be a prince, and to understand the nature of the prince, one must be of the people.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli16 = Quote.create({ content: "A sign of intelligence is ans awareness of one's own ignorance.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli17 = Quote.create({ content: "I believe it to be most true that it seldom happens that men rise from low condition to high rank without employing either force or fraud.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli18 = Quote.create({ content: "When you disarm the people, you commence to offend them and show that you distrust them either through cowardice or lack of confidence, and both of there opinions generate hatred.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli19 = Quote.create({ content: "Men rise from one ambition to another: first, they seek to secure themselves against attack, and then they attack others.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli20 = Quote.create({ content: "The promise given was a necessity of the past: the word broken is a necessity of the present.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli21 = Quote.create({ content: "The main foundations of every state, new states as well as ancient or composite ones, are good laws and good arms you cannot have good laws without good arms, and where there are good arms, good laws inevitably follow.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli22 = Quote.create({ content: "Good order and discipline in any army are to be depeneded upon more than courage alone.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli23 = Quote.create({ content: "May princes know then that they begin to lose (their) state at that hour in which they begin to break the laws and those custums and usages that are ancient and under which men have lived for a long time.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli24 = Quote.create({ content: "Wars begin when you will, but they do not end when you please.", author: 'Niccolo Machiavelli', quote_details: "" })
machiavelli25 = Quote.create({ content: "A return to first principles in a republic is sometimes cause by the simple virtues of one man. His good example has such an influence that the good men strive to imitate him, and the wicked are ashamed to lead a life so contrary to his example.", author: 'Niccolo Machiavelli', quote_details: "" })


# KISSINGER
kissinger1 = Quote.create({ content: "It's not a matter of what is true that counts but a matter of what is perceived to be true.", author: 'Henry Kissinger', quote_details: "" })





# DARWIN
darwin1 = Quote.create({ content: 'It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.', author: 'Charles Darwin', quote_details: '1809' })
darwin2 = Quote.create({ content: "The love for all living creatures is the most noble attribute of man.", author: 'Charles Darwin', quote_details: "" })
darwin3 = Quote.create({ content: "If I had my life to live over again, I would have made a rule to read some poetry and listen to some music at least once every week.", author: 'Charles Darwin', quote_details: "" })
darwin4 = Quote.create({ content: "One general law, leading to the advancement of all organic beings, namely, multiply, vary, let the strongest live and the weakest die.", author: 'Charles Darwin', quote_details: "" })
darwin5 = Quote.create({ content: "The more one thinks, the more one feels the hopeless immensity of man's ignorance.", author: 'Charles Darwin', quote_details: "" })
darwin6 = Quote.create({ content: "If everyone were cast in the same mold, there would be no such thinkg as beauty.", author: 'Charles Darwin', quote_details: "" })
darwin7 = Quote.create({ content: "Ignorance more frequently begets confidence than does knowledge: it is those who know little, not those who know much, who so positively assert that this or that problem will never be solved by science.", author: 'Charles Darwin', quote_details: "" })
darwin8 = Quote.create({ content: "The very essence of instinct is that it's followed independently of reason.", author: 'Charles Darwin', quote_details: "" })
darwin9 = Quote.create({ content: "As a child, I often wrote deliberate nonsense to surprise others.", author: 'Charles Darwin', quote_details: "" })
darwin10 = Quote.create({ content: "A moral being is one who is capable of reflecting on his past actions and their motives - of approving of some and disapproving of others.", author: 'Charles Darwin', quote_details: "" })

# James Matthew Barrie
jamesMBarrie1 = Quote.create({ content: 'We never understand how little we need in this world until we know the loss of it.', author: 'James Matthew Barrie', quote_details: '`Margaret Ogilvy`, 1897' })
jamesMBarrie2 = Quote.create({ content: 'The moment you doubt whether you can fly, you cease for ever to be able to do it.', author: 'James Matthew Barrie', quote_details: 'Peter Pan' })
jamesMBarrie3 = Quote.create({ content: "Dreams do come true, if we only wish hard enough. You can have anything in life if you will sacrifice everything else for it.", author: 'James Matthew Barrie', quote_details: 'Peter Pan' })
jamesMBarrie4 = Quote.create({ content: "When a new baby laughs for the first time a new fairy is born, and as there are always new babies there always new fairies. They live in nests on the tops of trees; and the mauve ones are boys and the white ones are girls, and the blue ones are just little sillies who are not sure that they are.", author: 'James Matthew Barrie', quote_details: 'Peter Pan' })
jamesMBarrie5 = Quote.create({ content: "So come with me, where dreams are born, and time is never planned. Just think of happy things, and your heart will fly on wings, forever, in Never Never Land.", author: 'James Matthew Barrie', quote_details: 'Peter Pan' })
jamesMBarrie6 = Quote.create({ content: "I am not young enough to know everything.", author: 'James Matthew Barrie', quote_details: "" })
jamesMBarrie7 = Quote.create({ content: "", author: 'James Matthew Barrie', quote_details: 'Love is not blind; it is an extra eye, which shows us what is most worthy of regard.' })
jamesMBarrie8 = Quote.create({ content: "If growing up means it would be beneath my dignity to climb a tree, I'll never grow up, never grow up, never grow up! Not me!", author: 'James Matthew Barrie', quote_details: 'Peter Pan' })
jamesMBarrie9 = Quote.create({ content: "The life of every man is a diary in which he means to write one story, and writes another; and hist humblest hour is when he compares the volume as it is with what he vowed to make it.", author: 'James Matthew Barrie', quote_details: '`The Little Minister`' })
jamesMBarrie10 = Quote.create({ content: "It is not in doing what you like, but in liking what you do that is the secret of happiness.", author: 'James Matthew Barrie', quote_details: 'Peter Pan' })


# BROTHERS GRIMM
# grimm1 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm2 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm3 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm4 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm5 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm6 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm7 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm8 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm9 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })
# grimm10 = Quote.create({ content: "", author: 'Jacob and Wilhelm Grimm (Brothers Grimm)', quote_details: "" })



# HARRY POTTER
hp1 = Quote.create({ content: 'Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.', author: 'J.K. Rowling', quote_details: '-Albus Dumbledore, `Harry Potter` Series' })
hp2 = Quote.create({ content: 'Working hard is important but there is something that matters even more; believing in yourself.', author: 'J.K. Rowling', quote_details: '-Harry Potter, `Harry Potter` Series' })
hp3 = Quote.create({ content: "We've all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are.", author: 'J.K. Rowling', quote_details: '-Serius Black, `Harry Potter` Series' })
hp4 = Quote.create({ content: 'It takes a great deal of bravery to stand up to our enemies but, just as much to stand up to our friends.', author: 'J.K. Rowling', quote_details: '`Harry Potter` Series' })
hp5 = Quote.create({ content: "Things we lose have a way of coming back to us in the end, if not always in the way we expect.", author: 'J.K. Rowling', quote_details: '-Luna Lovegood, `Harry Potter` Series' })
hp6 = Quote.create({ content: "If you want to know what a man's life, take a good look at how he treats his inferiors, not his equals.", author: 'J.K. Rowling', quote_details: '`Harry Potter` Series' })
hp7 = Quote.create({ content: "Soon we must all face the choice between what is right and what is easy.", author: 'J.K. Rowling', quote_details: '-Albus Dumbledore, `Harry Potter` Series' })
hp8 = Quote.create({ content: "The ones that love us never really leave us. You can always find them in here.", author: 'J.K. Rowling', quote_details: '-Serius Black, `Harry Potter` Series' })
hp9 = Quote.create({ content: "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", author: 'J.K. Rowling', quote_details: '-Albus Dumbledore`Harry Potter` Series' })
hp10 = Quote.create({ content: "I'm going to be before either of you come up with another clever idea to get us killed - or worse, expelled.", author: 'J.K. Rowling', quote_details: '-Hermione Granger, `Harry Potter` Series' })



# Game of Thrones
got1 = Quote.create({ content: "When you tear out a man's tongue, you are not proving him a liar, you're only telling the world that you fear what he might say.", author: 'George R. R. Martin', quote_details: '- Tyrion Lannister from `Game of Thrones: Song of Ice and Fire Series`' })
got2 = Quote.create({ content: "Power resides where men believe it resides. It's a trick. A shadow on the wall. And a very small man can cast a very large shadow.", author: 'George R. R. Martin', quote_details: '-Lord Varys, `Game of Thrones: Song of Ice and Fire`' })
got3 = Quote.create({ content: "When enough people make false promises; words stop meaning anything.", author: 'George R. R. Martin', quote_details: '-John Snow, `Game of Thrones: Song of Ice and Fire`' })

got4 = Quote.create({ content: "Chaos isn't a gaping pit waiting to swallow us all. Chaos is a ladder. Many who try to climb it fail and never get to try again. The fall breaks them. And some are given the chance to climb, but they refuse. Or gods. Or love. Illusions! Only the ladder is real! The climb is all there is!", author: 'George R. R. Martin', quote_details: "-Petyr `Littlefinger` Baelish, `Game of Thrones: Song of Ice and Fire`" })

got5 = Quote.create({ content: "A wise man once said that you should never believe a thing simply because you want to believe it.", author: 'George R. R. Martin', quote_details: '-Tyrion Lannister, `Game of Thrones: Song of Ice and Fire`' })
got6 = Quote.create({ content: "When you play the game of thrones you win or you die. There is no middle ground.", author: 'George R. R. Martin', quote_details: '-Cersei Lannister, `Game of Thrones: Song of Ice and Fire`' })
got7 = Quote.create({ content: "All my life men like you sneered at me. And all my life I've been knocking men like you into the dust.", author: 'George R. R. Martin', quote_details: '-Brienne of Tarth, `Game of Thrones: Song of Ice and Fire`' })
got8 = Quote.create({ content: "The man who passes the sentence should swing the sword. If you would take a man's life, you owe it to him to look into his eyes and hear his final words. And if you cannot bear to do that, then perhaps the man does not deserve to die.", author: 'George R. R. Martin', quote_details: '-Eddard Stark, `Game of Thrones: Song of Ice and Fire`' })
got9 = Quote.create({ content: "Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.", author: 'George R. R. Martin', quote_details: '`Game of Thrones: Song of Ice and Fire`' })
got10 = Quote.create({ content: "The only time a man can be brave is when he is afraid.", author: 'George R. R. Martin', quote_details: '-Eddard Stark`Game of Thrones: Song of Ice and Fire`' })
got11 = Quote.create({ content: "It's easy to confuse what is with what ought to be, especially when what is has worked out in your favor.", author: 'George R. R. Martin', quote_details: '`Game of Thrones: Song of Ice and Fire`' })

got12 = Quote.create({ content: "When the snows fall, and the white winds blow, the lone wolf dies, but the pack survives.", author: 'George R. R. Martin', quote_details: '-Sansa Stark, `Game of Thrones: Song of Ice and Fire`' })

got13 = Quote.create({ content: "What is honor compared to a woman's love? What is duty against the feel of a newborn son in your arms... or the memory of a brother's smile? Wind and words. Wind and words. We are only human, and the gods have fashioned us for love. That is our great glory, and our great tragedy.", author: 'George R. R. Martin', quote_details: '-Aemon Targaryen, `Game of Thrones: Song of Ice and Fire`' })

got14 = Quote.create({ content: "It is a big and beautiful world. Most of us live and die in the same corner where we were born and never get to see any of it. I don't want to be most of us.", author: 'George R. R. Martin', quote_details: '-Oberyn Martell, `Game of Thrones: Song of Ice and Fire`' })

got15 = Quote.create({ content: "Death is the enemy. The first enemy and the last. The enemy always wins, and we still need to fight him.", author: 'George R. R. Martin', quote_details: '-Beric Dondarrion, `Game of Thrones: Song of Ice and Fire`' })
got16 = Quote.create({ content: "Everybody dies sooner or later. Don't worry about your death, worry about your life. Take charge of your life for as long as it lasts.", author: 'George R. R. Martin', quote_details: '-Petyr Baelish, `Game of Thrones: Song of Ice and Fire`' })
got17 = Quote.create({ content: "I trust the eyes of an honest man more than I trust what everybody knows.", author: 'George R. R. Martin', quote_details: '-Tyrion Lannister, `Game of Thrones: Song of Ice and Fire`' })
got18 = Quote.create({ content: "A day will come when you think yourself safe and happy, and suddenly your will turn to ashes in your mouth, and you'll know the debt is paid.", author: 'George R. R. Martin', quote_details: '-Tyrion Lannister, `Game of Thrones: Song of Ice and Fire`' })
got19 = Quote.create({ content: "The greatest fools are often times more clever than the men who laugh at them.", author: 'George R. R. Martin', quote_details: '-Tywin Lannister, `Game of Thrones: Song of Ice and Fire`' })

got20 = Quote.create({ content: "A reader lives a thousand lives before he dies. The man who doesn't read lives only one.", author: 'George R. R. Martin', quote_details: '-Jojen Reed, `Game of Thrones: Song of Ice and Fire`' })
